// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfHt2N0OPyIldDZDx7szBoqHRa-fsmcE',
    appId: '1:892277497846:web:feed6beab1e359843e31d7',
    messagingSenderId: '892277497846',
    projectId: 'installdressr',
    authDomain: 'installdressr.firebaseapp.com',
    storageBucket: 'installdressr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoFRA0cw1SWkV-1x9Frol0--vMxHDtxKQ',
    appId: '1:892277497846:android:59277649c41b6e753e31d7',
    messagingSenderId: '892277497846',
    projectId: 'installdressr',
    storageBucket: 'installdressr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYOYS9YzKiy6lCg5RgXyrv8J5ts5SX6U',
    appId: '1:892277497846:ios:e9c7a4de4aa6b8f53e31d7',
    messagingSenderId: '892277497846',
    projectId: 'installdressr',
    storageBucket: 'installdressr.appspot.com',
    iosBundleId: 'com.installdressr.app',
  );
}
